import { useMemo } from 'react'
import type { MatchEvent, Team } from '@volleystats/shared'
import { ACTION_LABELS } from '@volleystats/shared'
import { cn } from '@/lib/utils'
import { isAwayPlayerId, getAwayPlayerDisplayName } from '@/lib/awayPlayers'

// ─── Compact Timeline Card ──────────────────────────────────────

function MiniTimelineCard({
  event,
  playerName,
  playerNumber,
  isHome,
}: {
  event: MatchEvent
  playerName: string
  playerNumber: string
  isHome: boolean
}) {
  const isSuccess = event.result === 'success'
  const isError = event.result === 'error'

  const qualityLabel = getQualityLabel(event)
  const actionLabel = qualityLabel || ACTION_LABELS[event.action]

  return (
    <div
      className={cn(
        'rounded-xl p-2.5 backdrop-blur-md',
        'bg-white/[0.03] border border-white/10 shadow-[0_4px_30px_rgba(0,0,0,0.1)]',
        isHome ? 'border-r-[3px] border-r-primary' : 'border-l-[3px] border-l-pink-500',
      )}
    >
      <div className={cn('flex items-center gap-2', isHome ? 'flex-row-reverse' : 'flex-row')}>
        {/* Player badge */}
        <div
          className={cn(
            'flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-[9px] font-bold text-white shadow-md',
            isHome
              ? 'bg-primary shadow-primary/30'
              : 'bg-pink-500 shadow-pink-500/30',
          )}
        >
          {playerNumber}
        </div>
        <span className={cn('text-[10px] font-semibold text-slate-400 truncate', isHome ? 'text-right' : 'text-left')}>
          {playerName}
        </span>
      </div>
      <div className={cn('mt-1', isHome ? 'text-right' : 'text-left')}>
        <span
          className={cn(
            'inline-block rounded-full px-1.5 py-0.5 text-[8px] font-bold uppercase tracking-wider',
            isSuccess && 'bg-success/20 text-success',
            isError && 'bg-error/20 text-error',
            !isSuccess && !isError && 'bg-white/10 text-text-muted',
          )}
        >
          {isError ? 'Ошибка' : actionLabel}
        </span>
      </div>
    </div>
  )
}

// ─── Mini Score Pin ─────────────────────────────────────────────

function MiniScorePin({ scoreHome, scoreAway, isHomePoint }: { scoreHome: number; scoreAway: number; isHomePoint: boolean }) {
  return (
    <div className="absolute left-1/2 top-1/2 z-10 -translate-x-1/2 -translate-y-1/2">
      <div
        className={cn(
          'rounded-full px-2 py-0.5 text-[9px] font-bold',
          'bg-background border',
          isHomePoint
            ? 'border-primary/40 text-primary shadow-[0_0_12px_rgba(60,131,246,0.3)]'
            : 'border-white/20 text-slate-300',
        )}
      >
        {scoreHome}:{scoreAway}
      </div>
    </div>
  )
}

// ─── Helpers ────────────────────────────────────────────────────

function getQualityLabel(event: MatchEvent): string {
  const q = event.meta?.quality
  if (!q) return ''
  const labels: Record<string, string> = {
    ace: 'Эйс',
    pressure: 'Услож',
    in_play: 'В игру',
    serve_error: 'Ош.подачи',
    excellent: '++',
    positive: '+',
    ok: '!',
    negative: '−',
    over: '/',
    half: '=',
    reception_error: 'Ош.приёма',
    attack_error: 'Ош.атаки',
    attack_blocked: 'Уд.в блок',
    block_error: 'Ош.блока',
    defense_error: 'Ош.защиты',
    setting_error: 'Ош.передачи',
  }
  return labels[q] || q
}

// ─── Main Component ─────────────────────────────────────────────

export function EventFeed({
  events,
  homeTeam,
  awayTeam,
  homeTeamId,
  maxEvents = 10,
}: {
  events: MatchEvent[]
  homeTeam: Team | undefined
  awayTeam: Team | undefined
  homeTeamId: string
  maxEvents?: number
}) {
  const recentEvents = useMemo(() => {
    return events
      .filter((e) => !e.meta?.autoGenerated)
      .slice(-maxEvents)
      .reverse()
  }, [events, maxEvents])

  const getPlayerInfo = (teamId: string, playerId: string): { name: string; number: string } => {
    if (playerId === 'opponent-error') return { name: 'Соперник', number: '??' }
    if (isAwayPlayerId(playerId)) {
      const name = getAwayPlayerDisplayName(playerId)
      const m = playerId.match(/\d+/)
      return { name, number: m ? m[0] : '?' }
    }
    const team = teamId === homeTeamId ? homeTeam : awayTeam
    const player = team?.players.find((p) => p.id === playerId)
    if (!player) return { name: '?', number: '?' }
    return { name: player.lastName, number: String(player.number).padStart(2, '0') }
  }

  if (recentEvents.length === 0) {
    return (
      <div className="px-3 py-4 text-center text-xs text-text-muted">
        Нет событий
      </div>
    )
  }

  return (
    <div className="px-3">
      {/* Team legend */}
      <div className="mb-3 flex items-center justify-between px-1 text-[8px] font-bold uppercase tracking-widest opacity-50">
        <span className="text-primary">{homeTeam?.shortName || homeTeam?.name || 'Дом'}</span>
        <span className="text-[7px] text-text-muted">События</span>
        <span className="text-pink-500">{awayTeam?.shortName || awayTeam?.name || 'Гости'}</span>
      </div>

      {/* Timeline */}
      <div className="relative">
        {/* Central timeline line */}
        <div
          className="absolute left-1/2 top-0 bottom-0 -translate-x-1/2 w-[1.5px] pointer-events-none opacity-25"
          style={{
            background: 'linear-gradient(to bottom, rgba(60,131,246,0.1), rgba(60,131,246,0.8), rgba(60,131,246,0.1))',
            boxShadow: '0 0 10px rgba(60,131,246,0.4)',
          }}
        />

        <div className="space-y-4 relative">
          {recentEvents.map((event, idx) => {
            const isHome = event.teamId === homeTeamId
            const info = getPlayerInfo(event.teamId, event.playerId)
            const isScoring = event.result === 'success' || event.result === 'error'

            // Check if score changed from previous event
            let showScorePin = false
            if (isScoring) {
              let prevScore = { home: 0, away: 0 }
              for (let j = idx + 1; j < recentEvents.length; j++) {
                const prev = recentEvents[j]
                if (prev) {
                  prevScore = { home: prev.scoreHome, away: prev.scoreAway }
                  break
                }
              }
              showScorePin = event.scoreHome !== prevScore.home || event.scoreAway !== prevScore.away
            }

            const isHomePoint = showScorePin && (
              (isHome && event.result === 'success') ||
              (!isHome && event.result === 'error')
            )

            return (
              <div key={event.id} className="relative grid grid-cols-2 gap-4 items-center">
                {/* Left (home) */}
                <div className={cn(!isHome && 'invisible')}>
                  {isHome && (
                    <MiniTimelineCard
                      event={event}
                      playerName={info.name}
                      playerNumber={info.number}
                      isHome={true}
                    />
                  )}
                </div>

                {/* Right (away) */}
                <div className={cn(isHome && 'invisible')}>
                  {!isHome && (
                    <MiniTimelineCard
                      event={event}
                      playerName={info.name}
                      playerNumber={info.number}
                      isHome={false}
                    />
                  )}
                </div>

                {/* Score pin */}
                {showScorePin && (
                  <MiniScorePin
                    scoreHome={event.scoreHome}
                    scoreAway={event.scoreAway}
                    isHomePoint={isHomePoint}
                  />
                )}
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
