import { useMemo } from 'react'
import type { Match, MatchEvent, Team, RallyPhase } from '@volleystats/shared'
import { RALLY_PHASE_LABELS } from '@volleystats/shared'

function LiveDot() {
  return (
    <span className="relative flex h-2 w-2">
      <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-error opacity-75" />
      <span className="relative inline-flex h-2 w-2 rounded-full bg-error" />
    </span>
  )
}

export function ScoreBar({
  match,
  homeTeam,
  awayTeam,
  currentSetScore,
  rallyPhase,
  servingTeamId,
  events,
}: {
  match: Match
  homeTeam: Team | undefined
  awayTeam: Team | undefined
  currentSetScore: { home: number; away: number }
  rallyPhase: RallyPhase
  servingTeamId: string | undefined
  events: MatchEvent[]
}) {
  const finishedSets = match.sets.filter((s) => s.isFinished)
  const homeSetsWon = finishedSets.filter((s) => s.scoreHome > s.scoreAway).length
  const awaySetsWon = finishedSets.filter((s) => s.scoreAway > s.scoreHome).length

  const isHomeServing = servingTeamId === match.homeTeamId

  const stats = useMemo(() => {
    const realEvents = events.filter(e => !e.meta?.autoGenerated)

    const compute = (teamId: string) => {
      const te = realEvents.filter(e => e.teamId === teamId)
      const serves = te.filter(e => e.action === 'serve')
      const attacks = te.filter(e => e.action === 'attack')
      const blocks = te.filter(e => e.action === 'block')
      const receptions = te.filter(e => e.action === 'reception')

      return {
        aces: serves.filter(e => e.result === 'success').length,
        servePressure: serves.filter(e => e.meta?.quality === 'pressure').length,
        serveErrors: serves.filter(e => e.result === 'error').length,
        attackPlus: attacks.filter(e => e.result === 'success').length,
        attackMinus: attacks.filter(e => e.result === 'error').length,
        blockPlus: blocks.filter(e => e.result === 'success').length,
        blockMinus: blocks.filter(e => e.result === 'error').length,
        receptionPct: receptions.length > 0
          ? Math.round((receptions.filter(e => e.result === 'success').length / receptions.length) * 100)
          : null,
      }
    }

    return {
      home: compute(match.homeTeamId),
      away: compute(match.awayTeamId),
    }
  }, [events, match.homeTeamId, match.awayTeamId])

  return (
    <div className="sticky top-0 z-50 border-b border-border bg-background/90 px-3 pt-safe backdrop-blur-xl">
      {/* Sets won + current set */}
      <div className="flex items-center justify-between pb-1 pt-2">
        <div className="flex items-center gap-1.5">
          {finishedSets.map((s) => (
            <span key={s.number} className="text-[10px] text-text-muted">
              {s.scoreHome}:{s.scoreAway}
            </span>
          ))}
        </div>
        <div className="flex items-center gap-1.5">
          <LiveDot />
          <span className="text-[10px] font-medium uppercase tracking-wider text-text-muted">
            Сет {match.currentSet}
          </span>
        </div>
        <span className="text-xs font-bold text-text-muted">
          {homeSetsWon}:{awaySetsWon}
        </span>
      </div>

      {/* Main score */}
      <div className="flex items-center justify-center gap-4 pb-1">
        <div className="flex flex-1 items-center justify-end gap-2">
          {isHomeServing && <span className="text-xs">🏐</span>}
          <span className="text-sm font-medium text-text-secondary truncate max-w-[100px]">
            {homeTeam?.shortName || homeTeam?.name || '—'}
          </span>
        </div>
        <div className="flex items-baseline gap-2">
          <span className="text-4xl font-black tabular-nums text-text-primary">{currentSetScore.home}</span>
          <span className="text-xl text-text-muted">:</span>
          <span className="text-4xl font-black tabular-nums text-text-primary">{currentSetScore.away}</span>
        </div>
        <div className="flex flex-1 items-center gap-2">
          <span className="text-sm font-medium text-text-secondary truncate max-w-[100px]">
            {awayTeam?.shortName || awayTeam?.name || '—'}
          </span>
          {!isHomeServing && <span className="text-xs">🏐</span>}
        </div>
      </div>

      {/* Phase indicator + timeouts/subs */}
      <div className="flex items-center justify-between pb-1">
        <span className="text-[10px] text-text-muted">
          ТО:{match.homeTimeouts} Зам:{match.homeSubstitutions}
        </span>
        <span className="rounded-full bg-primary/20 px-2.5 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-primary">
          {RALLY_PHASE_LABELS[rallyPhase]}
        </span>
        <span className="text-[10px] text-text-muted">
          ТО:{match.awayTimeouts} Зам:{match.awaySubstitutions}
        </span>
      </div>

      {/* Live stats grid */}
      <div className="grid grid-cols-[1fr_auto_1fr] gap-x-3 pb-2 text-[11px] tabular-nums">
        {/* Подача */}
        <div className="flex justify-end gap-1.5">
          <span className="text-success">{stats.home.aces}э</span>
          <span className="text-text-muted">{stats.home.servePressure}у</span>
          <span className="text-error">{stats.home.serveErrors}о</span>
        </div>
        <span className="text-[10px] text-text-muted/60 font-medium">Под</span>
        <div className="flex gap-1.5">
          <span className="text-success">{stats.away.aces}э</span>
          <span className="text-text-muted">{stats.away.servePressure}у</span>
          <span className="text-error">{stats.away.serveErrors}о</span>
        </div>

        {/* Атака */}
        <div className="flex justify-end gap-1.5">
          <span className="text-success">{stats.home.attackPlus}+</span>
          <span className="text-error">{stats.home.attackMinus}−</span>
        </div>
        <span className="text-[10px] text-text-muted/60 font-medium">Ата</span>
        <div className="flex gap-1.5">
          <span className="text-success">{stats.away.attackPlus}+</span>
          <span className="text-error">{stats.away.attackMinus}−</span>
        </div>

        {/* Блок */}
        <div className="flex justify-end gap-1.5">
          <span className="text-success">{stats.home.blockPlus}+</span>
          <span className="text-error">{stats.home.blockMinus}−</span>
        </div>
        <span className="text-[10px] text-text-muted/60 font-medium">Бло</span>
        <div className="flex gap-1.5">
          <span className="text-success">{stats.away.blockPlus}+</span>
          <span className="text-error">{stats.away.blockMinus}−</span>
        </div>

        {/* Приём */}
        <div className="flex justify-end">
          <span className={stats.home.receptionPct !== null ? 'text-primary' : 'text-text-muted/40'}>
            {stats.home.receptionPct !== null ? `${stats.home.receptionPct}%` : '—'}
          </span>
        </div>
        <span className="text-[10px] text-text-muted/60 font-medium">Пр</span>
        <div className="flex">
          <span className={stats.away.receptionPct !== null ? 'text-warning' : 'text-text-muted/40'}>
            {stats.away.receptionPct !== null ? `${stats.away.receptionPct}%` : '—'}
          </span>
        </div>
      </div>
    </div>
  )
}
