import { useMemo } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { db } from '@/db/database'
import { cn } from '@/lib/utils'
import { useParams, Link } from 'react-router'
import type { Match, Team, MatchEvent, TeamMatchStats } from '@volleystats/shared'
import { ACTION_LABELS } from '@volleystats/shared'
import { ArrowLeft, BarChart3, FileText, Clock, Download } from 'lucide-react'
import { exportMatchProtocol } from '@/lib/exportProtocol'

interface StatRow {
  label: string
  homeValue: number
  awayValue: number
  isPercent?: boolean
  section?: string
}

function ComparisonBar({ stat }: { stat: StatRow }) {
  const max = Math.max(stat.homeValue, stat.awayValue, 1)
  const homeWidth = (stat.homeValue / max) * 100
  const awayWidth = (stat.awayValue / max) * 100
  const format = (v: number) => (stat.isPercent ? `${v}%` : String(v))

  return (
    <div className="mb-4">
      <div className="mb-1.5 text-center text-[10px] font-semibold uppercase tracking-wider text-text-muted">
        {stat.label}
      </div>
      <div className="flex items-center gap-2">
        {/* Home value */}
        <span className="w-14 text-right text-sm font-bold tabular-nums text-primary">
          {format(stat.homeValue)}
        </span>
        {/* Bars */}
        <div className="flex flex-1 items-center gap-1">
          {/* Home bar (grows right-to-left) */}
          <div className="flex h-5 flex-1 justify-end">
            <div
              className="rounded-l-full bg-primary transition-all duration-500"
              style={{ width: `${homeWidth}%` }}
            />
          </div>
          {/* Away bar (grows left-to-right) */}
          <div className="flex h-5 flex-1 justify-start">
            <div
              className="rounded-r-full bg-warning transition-all duration-500"
              style={{ width: `${awayWidth}%` }}
            />
          </div>
        </div>
        {/* Away value */}
        <span className="w-14 text-left text-sm font-bold tabular-nums text-warning">
          {format(stat.awayValue)}
        </span>
      </div>
    </div>
  )
}

const EMPTY_STATS: DetailedStats = {
  teamId: '',
  matchId: '',
  totalPoints: 0,
  earnedPoints: 0,
  errors: 0,
  aces: 0,
  servePercent: 0,
  attackPercent: 0,
  blockPercent: 0,
  receptionPercent: 0,
  serveTotal: 0,
  servePressure: 0,
  serveInPlay: 0,
  serveErrors: 0,
  attackTotal: 0,
  attackPoints: 0,
  attackErrors: 0,
  attackBlocked: 0,
  blockTotal: 0,
  blockPoints: 0,
  blockErrors: 0,
  receptionTotal: 0,
  receptionExcellent: 0,
  receptionPositive: 0,
  receptionNeutral: 0,
  receptionErrors: 0,
  defenseTotal: 0,
  defenseGood: 0,
  defenseErrors: 0,
}

interface DetailedStats extends TeamMatchStats {
  serveTotal: number
  servePressure: number
  serveInPlay: number
  serveErrors: number
  attackTotal: number
  attackPoints: number
  attackErrors: number
  attackBlocked: number
  blockTotal: number
  blockPoints: number
  blockErrors: number
  receptionTotal: number
  receptionExcellent: number
  receptionPositive: number
  receptionNeutral: number
  receptionErrors: number
  defenseTotal: number
  defenseGood: number
  defenseErrors: number
}

function computeStatsFromEvents(
  events: MatchEvent[],
  homeTeamId: string,
  awayTeamId: string,
  matchId: string,
): { home: DetailedStats; away: DetailedStats } {
  // Filter out auto-generated mirror events to avoid double-counting
  const realEvents = events.filter((e) => !e.meta?.autoGenerated)

  const compute = (teamId: string): DetailedStats => {
    const teamEvents = realEvents.filter((e) => e.teamId === teamId)
    const opponentEvents = realEvents.filter((e) => e.teamId !== teamId)

    const serves = teamEvents.filter((e) => e.action === 'serve')
    const attacks = teamEvents.filter((e) => e.action === 'attack')
    const blocks = teamEvents.filter((e) => e.action === 'block')
    const receptions = teamEvents.filter((e) => e.action === 'reception')
    const defense = teamEvents.filter((e) => e.action === 'defense')

    const aces = serves.filter((e) => e.result === 'success').length
    const serveErrors = serves.filter((e) => e.result === 'error').length
    const servePressure = serves.filter((e) => e.meta?.quality === 'pressure').length
    const serveInPlay = serves.filter((e) => e.meta?.quality === 'in_play').length
    const attackPoints = attacks.filter((e) => e.result === 'success').length
    const attackErrors = attacks.filter((e) => e.result === 'error' && e.meta?.quality !== 'attack_blocked').length
    const attackBlocked = attacks.filter((e) => e.meta?.quality === 'attack_blocked').length
    const blockPoints = blocks.filter((e) => e.result === 'success').length
    const blockErrors = blocks.filter((e) => e.result === 'error').length
    const receptionExcellent = receptions.filter((e) => e.meta?.quality === 'excellent').length
    const receptionPositive = receptions.filter((e) => e.meta?.quality === 'positive').length
    const receptionNeutral = receptions.filter((e) => e.result === 'neutral').length
    const receptionErrors = receptions.filter((e) => e.result === 'error').length
    const receptionOk = receptions.filter((e) => e.result !== 'error').length
    const defenseGood = defense.filter((e) => e.result === 'success').length
    const defenseErrors = defense.filter((e) => e.result === 'error').length

    const earnedPoints = aces + attackPoints + blockPoints
    const errors = teamEvents.filter((e) => e.result === 'error').length
    const opponentErrors = opponentEvents.filter((e) => e.result === 'error').length

    return {
      teamId,
      matchId,
      totalPoints: earnedPoints + opponentErrors,
      earnedPoints,
      errors,
      aces,
      servePercent: serves.length > 0 ? Math.round(((serves.length - serveErrors) / serves.length) * 1000) / 10 : 0,
      attackPercent: attacks.length > 0 ? Math.round((attackPoints / attacks.length) * 1000) / 10 : 0,
      blockPercent: blocks.length > 0 ? Math.round((blockPoints / blocks.length) * 1000) / 10 : 0,
      receptionPercent: receptions.length > 0 ? Math.round((receptionOk / receptions.length) * 1000) / 10 : 0,
      serveTotal: serves.length,
      servePressure,
      serveInPlay,
      serveErrors,
      attackTotal: attacks.length,
      attackPoints,
      attackErrors,
      attackBlocked,
      blockTotal: blocks.length,
      blockPoints,
      blockErrors,
      receptionTotal: receptions.length,
      receptionExcellent,
      receptionPositive,
      receptionNeutral,
      receptionErrors,
      defenseTotal: defense.length,
      defenseGood,
      defenseErrors,
    }
  }

  return {
    home: compute(homeTeamId),
    away: compute(awayTeamId),
  }
}

export function MatchStatsPage() {
  const { matchId } = useParams<{ matchId: string }>()

  const match = useLiveQuery(() => (matchId ? db.matches.get(matchId) : undefined), [matchId])
  const events = useLiveQuery(
    () => (matchId ? db.matchEvents.where('matchId').equals(matchId).toArray() : []),
    [matchId],
  ) ?? []
  const homeTeam = useLiveQuery(
    () => (match?.homeTeamId ? db.teams.get(match.homeTeamId) : undefined),
    [match?.homeTeamId],
  )
  const awayTeam = useLiveQuery(
    () => (match?.awayTeamId ? db.teams.get(match.awayTeamId) : undefined),
    [match?.awayTeamId],
  )

  const stats = useMemo(() => {
    if (!match) return { home: { ...EMPTY_STATS }, away: { ...EMPTY_STATS } }
    return computeStatsFromEvents(events, match.homeTeamId, match.awayTeamId, match.id)
  }, [events, match])

  if (!match) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <div className="text-text-muted">Загрузка...</div>
      </div>
    )
  }

  const setsWonHome = match.sets.filter((s) => s.isFinished && s.scoreHome > s.scoreAway).length
  const setsWonAway = match.sets.filter((s) => s.isFinished && s.scoreAway > s.scoreHome).length
  const statusLabel = match.status === 'finished' ? 'ФИНАЛ' : match.status === 'live' ? 'LIVE' : 'SETUP'

  const statRows: StatRow[] = [
    // Общее
    { label: 'ВСЕГО ОЧКОВ', homeValue: stats.home.totalPoints, awayValue: stats.away.totalPoints, section: 'Общее' },
    { label: 'НАБРАНО ОЧКОВ', homeValue: stats.home.earnedPoints, awayValue: stats.away.earnedPoints },
    { label: 'ОШИБОК', homeValue: stats.home.errors, awayValue: stats.away.errors },
    // Подача
    { label: 'ПОДАЧ ВСЕГО', homeValue: stats.home.serveTotal, awayValue: stats.away.serveTotal, section: 'Подача' },
    { label: 'ЭЙСОВ', homeValue: stats.home.aces, awayValue: stats.away.aces },
    { label: 'УСЛОЖНЁННЫХ', homeValue: stats.home.servePressure, awayValue: stats.away.servePressure },
    { label: 'В ИГРУ', homeValue: stats.home.serveInPlay, awayValue: stats.away.serveInPlay },
    { label: 'ОШИБОК ПОДАЧИ', homeValue: stats.home.serveErrors, awayValue: stats.away.serveErrors },
    // Приём
    { label: 'ПРИЁМОВ ВСЕГО', homeValue: stats.home.receptionTotal, awayValue: stats.away.receptionTotal, section: 'Приём' },
    { label: '++ ОТЛИЧНЫЙ', homeValue: stats.home.receptionExcellent, awayValue: stats.away.receptionExcellent },
    { label: '+ ПОЗИТИВНЫЙ', homeValue: stats.home.receptionPositive, awayValue: stats.away.receptionPositive },
    { label: 'НЕЙТРАЛЬНЫЙ', homeValue: stats.home.receptionNeutral, awayValue: stats.away.receptionNeutral },
    { label: 'ОШИБОК ПРИЁМА', homeValue: stats.home.receptionErrors, awayValue: stats.away.receptionErrors },
    { label: '% ПРИЁМА', homeValue: stats.home.receptionPercent, awayValue: stats.away.receptionPercent, isPercent: true },
    // Атака
    { label: 'АТАК ВСЕГО', homeValue: stats.home.attackTotal, awayValue: stats.away.attackTotal, section: 'Атака' },
    { label: 'ОЧКОВ АТАКИ', homeValue: stats.home.attackPoints, awayValue: stats.away.attackPoints },
    { label: 'ОШИБОК АТАКИ', homeValue: stats.home.attackErrors, awayValue: stats.away.attackErrors },
    { label: 'УДАРОВ В БЛОК', homeValue: stats.home.attackBlocked, awayValue: stats.away.attackBlocked },
    { label: '% УСП. АТАК', homeValue: stats.home.attackPercent, awayValue: stats.away.attackPercent, isPercent: true },
    // Блок
    { label: 'БЛОКОВ ВСЕГО', homeValue: stats.home.blockTotal, awayValue: stats.away.blockTotal, section: 'Блок' },
    { label: 'ОЧКОВ БЛОКА', homeValue: stats.home.blockPoints, awayValue: stats.away.blockPoints },
    { label: 'ОШИБОК БЛОКА', homeValue: stats.home.blockErrors, awayValue: stats.away.blockErrors },
    // Защита
    { label: 'ЗАЩИТ ВСЕГО', homeValue: stats.home.defenseTotal, awayValue: stats.away.defenseTotal, section: 'Защита' },
    { label: 'УДАЧНЫХ', homeValue: stats.home.defenseGood, awayValue: stats.away.defenseGood },
    { label: 'ОШИБОК', homeValue: stats.home.defenseErrors, awayValue: stats.away.defenseErrors },
  ]

  return (
    <div className="px-4 pt-safe pb-24">
      {/* Header */}
      <div className="flex items-center gap-3 py-4">
        <Link to="/matches" className="rounded-full p-2 hover:bg-surface-light">
          <ArrowLeft className="h-5 w-5 text-text-secondary" />
        </Link>
        <h1 className="flex-1 text-lg font-bold">Статистика матча</h1>
        <button
          onClick={() => exportMatchProtocol(matchId!)}
          className="flex items-center gap-1.5 rounded-xl border border-border px-3 py-2 text-xs font-medium text-text-secondary transition hover:border-primary hover:text-primary"
        >
          <Download className="h-3.5 w-3.5" />
          Excel
        </button>
      </div>

      {/* Match Header */}
      <div className="glass mb-6 p-5">
        <div className="flex items-center justify-between">
          {/* Home Team */}
          <div className="flex flex-col items-center gap-2">
            <div className="flex h-14 w-14 items-center justify-center rounded-full bg-primary/20 text-sm font-bold text-primary">
              {homeTeam?.shortName || homeTeam?.name?.slice(0, 2).toUpperCase() || '??'}
            </div>
            <span className="max-w-[90px] text-center text-xs font-medium text-text-secondary">
              {homeTeam?.name ?? 'Хозяева'}
            </span>
          </div>

          {/* Score */}
          <div className="text-center">
            <div className="text-4xl font-extrabold tabular-nums text-text-primary">
              {setsWonHome}:{setsWonAway}
            </div>
            <span
              className={cn(
                'mt-1 inline-block rounded-full px-3 py-0.5 text-[10px] font-bold uppercase',
                match.status === 'live'
                  ? 'bg-success/20 text-success'
                  : 'bg-text-muted/20 text-text-muted',
              )}
            >
              {statusLabel}
            </span>
          </div>

          {/* Away Team */}
          <div className="flex flex-col items-center gap-2">
            <div className="flex h-14 w-14 items-center justify-center rounded-full bg-warning/20 text-sm font-bold text-warning">
              {awayTeam?.shortName || awayTeam?.name?.slice(0, 2).toUpperCase() || '??'}
            </div>
            <span className="max-w-[90px] text-center text-xs font-medium text-text-secondary">
              {awayTeam?.name ?? 'Гости'}
            </span>
          </div>
        </div>

        {/* Set scores */}
        <div className="mt-4 flex items-center justify-center gap-2">
          {match.sets
            .filter((s) => s.isFinished)
            .map((s, i) => (
              <span
                key={i}
                className="rounded-lg bg-surface-light px-3 py-1 text-xs font-mono font-medium tabular-nums text-text-secondary"
              >
                {s.scoreHome}:{s.scoreAway}
              </span>
            ))}
        </div>
      </div>

      {/* Tab bar */}
      <div className="mb-6 flex gap-1 rounded-xl bg-surface-light p-1">
        <Link
          to={`/matches/${matchId}/stats`}
          className="flex flex-1 items-center justify-center gap-1.5 rounded-lg bg-primary px-3 py-2.5 text-xs font-medium text-white shadow-lg"
        >
          <BarChart3 className="h-3.5 w-3.5" />
          Статистика
        </Link>
        <Link
          to={`/matches/${matchId}/stats`}
          className="flex flex-1 items-center justify-center gap-1.5 rounded-lg px-3 py-2.5 text-xs font-medium text-text-muted hover:text-text-secondary"
        >
          <FileText className="h-3.5 w-3.5" />
          Протокол
        </Link>
        <Link
          to={`/matches/${matchId}/timeline`}
          className="flex flex-1 items-center justify-center gap-1.5 rounded-lg px-3 py-2.5 text-xs font-medium text-text-muted hover:text-text-secondary"
        >
          <Clock className="h-3.5 w-3.5" />
          Ход игры
        </Link>
      </div>

      {/* Comparison Stats */}
      <div className="glass p-4">
        {/* Legend */}
        <div className="mb-4 flex items-center justify-between px-2">
          <div className="flex items-center gap-2">
            <div className="h-2.5 w-2.5 rounded-full bg-primary" />
            <span className="text-xs font-medium text-text-secondary">{homeTeam?.name ?? 'Хозяева'}</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-medium text-text-secondary">{awayTeam?.name ?? 'Гости'}</span>
            <div className="h-2.5 w-2.5 rounded-full bg-warning" />
          </div>
        </div>

        {statRows.map((stat) => (
          <div key={stat.label}>
            {stat.section && (
              <div className="mb-2 mt-4 first:mt-0 border-t border-border/50 pt-3">
                <span className="text-xs font-bold uppercase tracking-wider text-text-secondary">{stat.section}</span>
              </div>
            )}
            <ComparisonBar stat={stat} />
          </div>
        ))}
      </div>
    </div>
  )
}

export default MatchStatsPage;
