// === Позиции игроков ===
export type Position = 'setter' | 'opposite' | 'outside' | 'middle' | 'libero'

// === Действия ===
export type ActionType =
  | 'serve'
  | 'attack'
  | 'block'
  | 'reception'
  | 'defense'

export type ActionResult = 'success' | 'error' | 'neutral'

// === Зоны площадки (1-6 по волейбольной нумерации) ===
export type CourtZone = 1 | 2 | 3 | 4 | 5 | 6

// === Тип подачи ===
export type ServeType = 'float' | 'jump' | 'jump_float' | 'underhand'

// === Тип атаки ===
export type AttackType = 'spike' | 'tip' | 'roll' | 'pipe' | 'quick'

// === Фаза розыгрыша ===
export type RallyPhase = 'idle' | 'serve' | 'reception' | 'in_play' | 'rally_over'

// === Игрок ===
export interface Player {
  id: string
  number: number
  firstName: string
  lastName: string
  position: Position
  height?: number
  age?: number
  photoUrl?: string
}

// === Команда ===
export interface Team {
  id: string
  name: string
  shortName?: string
  city?: string
  logoUrl?: string
  players: Player[]
  createdAt: string
  updatedAt: string
}

// === Событие матча ===
export interface MatchEvent {
  id: string
  matchId: string
  rallyId?: string
  setNumber: number
  timestamp: number
  teamId: string
  playerId: string
  action: ActionType
  result: ActionResult
  zone?: CourtZone
  scoreHome: number
  scoreAway: number
  meta?: {
    serveType?: ServeType
    attackType?: AttackType
    attackZone?: CourtZone
    description?: string
    quality?: string
    autoGenerated?: boolean
  }
}

// === Специальные события (замены, таймауты) ===
export type SpecialEventType =
  | 'substitution'
  | 'timeout'
  | 'libero_in'
  | 'libero_out'
  | 'set_start'
  | 'set_end'

export interface SpecialEvent {
  id: string
  matchId: string
  setNumber: number
  timestamp: number
  teamId: string
  type: SpecialEventType
  meta?: {
    playerIn?: string
    playerOut?: string
    description?: string
  }
}

// === Сет ===
export interface MatchSet {
  number: number
  scoreHome: number
  scoreAway: number
  isFinished: boolean
  firstServeTeamId?: string
}

// === Расстановка на сет ===
export interface SetLineup {
  setNumber: number
  homeLineup: LineupEntry[]
  awayLineup: LineupEntry[]
}

// === Розыгрыш ===
export interface Rally {
  id: string
  matchId: string
  setNumber: number
  rallyNumber: number
  servingTeamId: string
  serverPlayerId: string
  scoreHomeBefore: number
  scoreAwayBefore: number
  scoreHomeAfter: number
  scoreAwayAfter: number
  pointWonByTeamId: string | null
  wasAce: boolean
  wasServeError: boolean
  wasReceptionError: boolean
  timestamp: number
}

// === Расстановка ===
export interface LineupEntry {
  playerId: string
  zone: CourtZone
  isLibero: boolean
}

// === Матч ===
export type MatchStatus = 'setup' | 'live' | 'finished'

export interface Match {
  id: string
  date: string
  homeTeamId: string
  awayTeamId: string
  sets: MatchSet[]
  currentSet: number
  status: MatchStatus
  homeLineup: LineupEntry[]
  awayLineup: LineupEntry[]
  setLineups?: SetLineup[]
  servingTeamId?: string
  firstServeTeamId?: string
  homeLiberoId?: string
  awayLiberoId?: string
  homeLiberoReplacedPlayerId?: string
  awayLiberoReplacedPlayerId?: string
  /** Array of libero IDs (up to 2). New field, preferred over homeLiberoId. */
  homeLiberoIds?: string[]
  /** Map of liberoId → replacedPlayerId for each libero currently on court. */
  homeLiberoReplacements?: Record<string, string>
  /** Array of away team libero IDs (generic players). */
  awayLiberoIds?: string[]
  homeTimeouts: number
  awayTimeouts: number
  homeSubstitutions: number
  awaySubstitutions: number
  createdAt: string
  updatedAt: string
}

// === Статистика игрока за матч ===
export interface PlayerMatchStats {
  playerId: string
  matchId: string
  points: number
  errors: number
  serveTotal: number
  serveErrors: number
  serveAces: number
  attackTotal: number
  attackErrors: number
  attackBlocked: number
  attackPoints: number
  blockTotal: number
  blockErrors: number
  blockPoints: number
  receptionTotal: number
  receptionErrors: number
  receptionExcellent: number
  defenseTotal: number
  defenseErrors: number
  defenseExcellent: number
}

// === Статистика команды за матч ===
export interface TeamMatchStats {
  teamId: string
  matchId: string
  totalPoints: number
  earnedPoints: number
  errors: number
  aces: number
  servePercent: number
  attackPercent: number
  blockPercent: number
  receptionPercent: number
}
